# Generated by Django 3.0.9 on 2020-08-05 01:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receiveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteNumber', models.CharField(max_length=10, unique=True)),
                ('customers', models.CharField(max_length=50)),
                ('receiveDay', models.DateField(auto_now_add=True)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('itemGroup', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=128, null=True)),
                ('check', models.CharField(max_length=128, null=True)),
                ('conclude', models.CharField(max_length=128, null=True)),
                ('deadline', models.DateField(default=datetime.date(2020, 8, 7))),
                ('note', models.TextField()),
                ('noteNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='baohanh.receiveTable')),
            ],
        ),
    ]
