# Generated by Django 3.0.9 on 2020-08-06 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baohanh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.BooleanField(choices=[(True, 'Xong'), (False, 'Chưa xong')], default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(),
        ),
    ]
