# Generated by Django 3.0.9 on 2020-08-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baohanh', '0003_auto_20200806_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(),
        ),
    ]
